name: Vitality
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '2.18.2'



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  pedometer: ^3.0.0
  syncfusion_flutter_charts: ^20.3.52
  google_mobile_ads: ^2.3.0
  smooth_page_indicator: ^1.0.0+2
  rflutter_alert: ^2.0.4
  flutter_plus: ^1.0.0
  percent_indicator: ^4.2.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  permission_handler: ^10.2.0
  wave: ^0.2.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - Assets/img-inicio.png
    - Assets/img-1.png
    - Assets/img-2.png
    - Assets/img-3.png
    - Assets/img-4.png
    - Assets/img-5.png
    - Assets/img-6.png

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins/Poppins-Light.ttf
      - asset: fonts/Poppins/Poppins-LightItalic.ttf
        weight: 300
      - asset: fonts/Poppins/Poppins-Regular.ttf
      - asset: fonts/Poppins/Poppins-Italic.ttf
        weight: 400
      - asset: fonts/Poppins/Poppins-Medium.ttf
      - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        weight: 500
  - family: Raleway
    fonts:
      - asset: fonts/Raleway-Regular.ttf
      - asset: fonts/Raleway-Italic.ttf
        style: italic
  - family: RobotoMono
    fonts:
      - asset: fonts/RobotoMono-Regular.ttf
      - asset: fonts/RobotoMono-Bold.ttf
        weight: 700