name: Vitality
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '2.19.2'



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  pedometer: ^3.0.0
  google_mobile_ads: ^2.3.0
  percent_indicator: ^4.2.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  permission_handler: ^10.2.0
  wave: ^0.2.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.4.43
  image_picker: ^0.8.6+1
  file_picker: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - Assets/img-inicio.png
    - Assets/img-1.png
    - Assets/img-2.png
    - Assets/img-3.png
    - Assets/img-4.png
    - Assets/img-5.png
    - Assets/img-6.png

fonts: